# Generated by Django 5.2.8 on 2025-11-23 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FastlyConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_token', models.CharField(blank=True, help_text='Fastly API token with Global access.', max_length=255, verbose_name='API token')),
                ('service_id', models.CharField(blank=True, help_text='Fastly service ID to control.', max_length=64, verbose_name='Service ID')),
                ('enabled', models.BooleanField(default=True)),
                ('soft_purge', models.BooleanField(default=True, help_text='Use Fastly Soft Purge by default.')),
                ('default_ttl', models.PositiveIntegerField(default=300, help_text='Surrogate-Control max-age (seconds).')),
                ('stale_while_revalidate', models.PositiveIntegerField(blank=True, default=0, help_text='stale-while-revalidate (seconds, 0 = disabled).')),
                ('stale_if_error', models.PositiveIntegerField(blank=True, default=0, help_text='stale-if-error (seconds, 0 = disabled).')),
                ('always_purged_keys', models.TextField(blank=True, help_text='One surrogate key per line to always purge with blog posts.')),
                ('webhook_url', models.URLField(blank=True, help_text='Optional webhook URL (e.g. Slack) to log purges.', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Fastly configuration',
                'verbose_name_plural': 'Fastly configuration',
            },
        ),
        migrations.CreateModel(
            name='PurgeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('method', models.CharField(choices=[('url', 'URL'), ('key', 'Surrogate key'), ('all', 'Purge all')], max_length=16)),
                ('target', models.CharField(blank=True, max_length=255)),
                ('success', models.BooleanField(default=False)),
                ('response_status', models.PositiveIntegerField(blank=True, null=True)),
                ('response_body', models.TextField(blank=True)),
            ],
        ),
    ]
