# Generated by Django 5.2.8 on 2025-11-25 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_fastly', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fastlyconfig',
            name='allow_full_cache_purges',
            field=models.BooleanField(default=False, help_text='Allow triggering full cache purges from the Django admin.'),
        ),
        migrations.AddField(
            model_name='fastlyconfig',
            name='api_endpoint',
            field=models.URLField(blank=True, help_text='Optional Fastly API endpoint override. Leave blank to use the default https://api.fastly.com.', max_length=255),
        ),
        migrations.AddField(
            model_name='fastlyconfig',
            name='cache_ttl',
            field=models.PositiveIntegerField(default=300, help_text='Cache-Control max-age (seconds).'),
        ),
        migrations.AddField(
            model_name='fastlyconfig',
            name='debug_mode',
            field=models.BooleanField(default=False, help_text='Enable extra debug logging for Fastly API calls.'),
        ),
        migrations.AddField(
            model_name='fastlyconfig',
            name='log_purges',
            field=models.BooleanField(default=True, help_text='Log Fastly purge requests to the PurgeLog table.'),
        ),
        migrations.AddField(
            model_name='fastlyconfig',
            name='webhook_active',
            field=models.BooleanField(default=False, help_text='Send purge notifications to the configured webhook.'),
        ),
        migrations.AddField(
            model_name='fastlyconfig',
            name='webhook_channel',
            field=models.CharField(blank=True, help_text='Optional channel identifier, e.g. #general.', max_length=80),
        ),
        migrations.AddField(
            model_name='fastlyconfig',
            name='webhook_username',
            field=models.CharField(blank=True, help_text='Optional display name for webhook messages (e.g. Slack username).', max_length=80),
        ),
    ]
