# Generated by Django 5.2.8 on 2025-11-26 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_fastly', '0002_fastlyconfig_allow_full_cache_purges_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EdgeModuleCors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False, help_text='Enable this Edge Module (CORS headers).')),
                ('allowed_origins', models.TextField(blank=True, help_text='Allowed origins, one per line. Use * to allow all origins (not recommended for production).')),
                ('allowed_methods', models.CharField(blank=True, default='GET, POST, OPTIONS', help_text='Comma-separated list of allowed methods, e.g. GET, POST, OPTIONS.', max_length=200)),
                ('allowed_headers', models.CharField(blank=True, default='Content-Type', help_text='Comma-separated list of allowed request headers, e.g. Content-Type, Authorization.', max_length=200)),
                ('expose_headers', models.CharField(blank=True, help_text='Comma-separated list of response headers to expose to JavaScript. Leave blank to expose none.', max_length=200)),
                ('max_age', models.PositiveIntegerField(default=600, help_text='Max age (in seconds) for preflight responses.')),
                ('allow_credentials', models.BooleanField(default=False, help_text='Whether to send Access-Control-Allow-Credentials: true. Requires a non-* origin.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Edge module: CORS headers',
                'verbose_name_plural': 'Edge modules: CORS headers',
            },
        ),
    ]
