# Generated by Django 5.2.8 on 2025-11-26 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_fastly', '0003_edgemodulecors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='edgemodulecors',
            name='allowed_origins',
        ),
        migrations.RemoveField(
            model_name='edgemodulecors',
            name='expose_headers',
        ),
        migrations.AddField(
            model_name='edgemodulecors',
            name='allowed_origins_regex',
            field=models.CharField(blank=True, help_text='Regex matching origins that are allowed to access this service. Do not include the leading "http://" or "https://".', max_length=255),
        ),
        migrations.AddField(
            model_name='edgemodulecors',
            name='origin_mode',
            field=models.CharField(choices=[('anyone', 'Allow anyone (*)'), ('regex-match', 'Regex matching set of origins')], default='anyone', help_text='What origins are allowed.', max_length=20),
        ),
        migrations.AlterField(
            model_name='edgemodulecors',
            name='allow_credentials',
            field=models.BooleanField(default=False, help_text='Whether to send Access-Control-Allow-Credentials: true. Requires a non-* origin (not yet used in VCL-equivalent logic).'),
        ),
        migrations.AlterField(
            model_name='edgemodulecors',
            name='allowed_headers',
            field=models.CharField(blank=True, help_text='Allowed HTTP headers that the requestor can use, e.g. Content-Type, Authorization.', max_length=200),
        ),
        migrations.AlterField(
            model_name='edgemodulecors',
            name='allowed_methods',
            field=models.CharField(blank=True, default='GET,HEAD,POST,OPTIONS', help_text='Allowed HTTP methods that the requestor can use, e.g. GET,HEAD,POST,OPTIONS.', max_length=200),
        ),
        migrations.AlterField(
            model_name='edgemodulecors',
            name='max_age',
            field=models.PositiveIntegerField(default=600, help_text='Max age (in seconds) for preflight responses (not yet used).'),
        ),
    ]
