# Generated by Django 5.2.9 on 2025-12-07 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_fastly', '0004_remove_edgemodulecors_allowed_origins_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EdgeModuleDisableCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False, help_text='Enable this Edge Module (Disable caching for selected paths).')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Edge module: Disable caching',
                'verbose_name_plural': 'Edge modules: Disable caching',
            },
        ),
        migrations.CreateModel(
            name='NoCacheRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path_pattern', models.CharField(help_text="VCL regex for req.url.path, e.g. '^/private/' or '\\.no-cache$'.", max_length=255)),
                ('mode', models.CharField(choices=[('browser', 'Browser only'), ('fastly', 'Fastly only'), ('both', 'Browser and Fastly')], default='both', help_text='Where to disable caching: browser, Fastly, or both.', max_length=16)),
                ('order', models.PositiveIntegerField(default=0, help_text='Optional order for applying rules (lower runs first).')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='django_fastly.edgemoduledisablecache')),
            ],
            options={
                'ordering': ('order', 'id'),
            },
        ),
    ]
